################################################################################
# vazaget makefile, originally Automatically-generated by eclipse
################################################################################

RM := rm -rf
CC := gcc
USER_OBJS :=
INC := -I /usr/include
CFLAGS := -DSSL_ENABLE
WARN_FLAGS := -Wall -Wextra -Werror -Wconversion
GPROF_FLAGS :=
		
LIBS := -lrt -lpthread -lz

ifeq ($(CFLAGS),-DSSL_ENABLE)
	LOCAL_LDFLAGS = -Llib \
		-lmbedtls \
		-lmbedx509 \
		-lmbedcrypto
	LIBS += $(LOCAL_LDFLAGS)
else
	LIBS +=
endif

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
config.c \
data_sender.c \
db.c \
html_parser.c \
http_parser.c \
main.c \
prints.c \
rx.c \
rx_chunk.c \
rx_analyze.c \
rx_range.c \
close.c \
timer.c \
ssl_vazaget.c \
buf_manager.c \
tx.c 

OBJS += \
./obj/config.o \
./obj/data_sender.o \
./obj/db.o \
./obj/html_parser.o \
./obj/http_parser.o \
./obj/main.o \
./obj/prints.o \
./obj/rx.o \
./obj/rx_chunk.o \
./obj/rx_analyze.o \
./obj/rx_range.o \
./obj/close.o \
./obj/timer.o \
./obj/ssl_vazaget.o \
./obj/buf_manager.o \
./obj/tx.o 

C_DEPS += \
./obj/config.d \
./obj/data_sender.d \
./obj/db.d \
./obj/html_parser.d \
./obj/http_parser.d \
./obj/main.d \
./obj/prints.d \
./obj/rx.d \
./obj/rx_chunk.d \
./obj/rx_analyze.d \
./obj/rx_range.d \
./obj/close.d \
./obj/timer.d \
./obj/ssl_vazaget.d \
./obj/buf_manager.d \
./obj/tx.d 

#DEPS += \
global.h \
parsers.h

# Each subdirectory must supply rules for building sources it contributes
./obj/%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) $(INC) $(WARN_FLAGS) -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" $(GPROF_FLAGS) -o "$@" "$<"	

# All Target
all: dbg

# target : dbg 
dbg: CFLAGS += -O0 -g3
dbg: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	$(CC) -rdynamic -o "vazaget" $(OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' ' 

# target : dbg_prof
# debug compilation + gprof profiler , we'll need GPROF_FLAGS -pg
dbg_prof: CFLAGS += -O0 -g3
dbg_prof: GPROF_FLAGS := -pg
dbg_prof: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	$(CC) -rdynamic $(GPROF_FLAGS) -o "vazaget" $(OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' ' 
	
# target : release 
release: CFLAGS += -O3
release: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	$(CC) -rdynamic -o "vazaget" $(OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' ' 
	
#target : clean
clean:
	-$(RM) $(OBJS)$(C_DEPS)$(EXECUTABLES) vazaget*
	-@echo ' '

#target : help
help :
	@echo ""
	@echo "make		- builds vazaget (default make = make dbg)"
	@echo "make dbg	- builds vazaget with dbg flags : -O0 -g3"
	@echo "make dbg_prof	- builds vazaget with dbg and gprof profiler flags : -O0 -g3 , -pg"
	@echo "make release	- builds vazaget with release flags : -O3"
	@echo "make clean	- clean executable, and object files"	
	@echo "make help	- this info"
	@echo ""

.PHONY: all clean dependents
.SECONDARY:


